/**
 * @swagger
 * tags:
 *  name: game
 *  description: game tag
 * /game:
 *  get:
 *      description: |
 *          Go to the game room on the websocket server on 1235 port
 *          Here you can see commands that we send via websockets:
 *          -   Command: 0 - move left
 *          -   Command: 1 - move right
 *          -   Command: 2 - move up
 *          -   Command: 3 - move down
 *          -   Command: 4 - fire
 *      tags: [game]
 *      responses:
 *          '200':
 *              description: Get game's site and then upgrade channel there
 *          '404':
 *              description: Front side file was not found
 * /api:
 *  get:
 *      description: Go to the site with API's description
 *      tags: [game]
 *      responses:
 *          '200':
 *              description: Get html that was generated by swaggerUI
 *          '404':
 *              description: File was not found
 * /doc:
 *  get:
 *      description: Go to game documentation
 *      tags: [game]
 *      responses:
 *          '200':
 *              description: Get html that was generated by jsdoc3
 *          '404':
 *              description: File was not found
 */