name: Greetings

on: [push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        npm i
        ./node_modules/mocha/bin/mocha unit-tests.js
